CREATE TABLE deck_strategy (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, win_condition TEXT, table_context TEXT, bracket INTEGER CHECK(bracket >= 1 AND bracket <= 4), budget_mode TEXT CHECK(budget_mode IN ('collection', 'budget', 'unrestricted')), budget_ceiling NUMERIC, frustration TEXT, strategy_notes TEXT, format_rules TEXT, health_overrides TEXT, user_id UUID NOT NULL, updated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_strategy_user_id ON deck_strategy(user_id);
CREATE TABLE deck_health (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, result_json TEXT NOT NULL, overall_status TEXT NOT NULL CHECK(overall_status IN ('green', 'amber', 'red')), user_id UUID NOT NULL, computed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_deck_health_user_id ON deck_health(user_id);
CREATE TABLE deck_documentation (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, strategy_playstyle TEXT, synergy_lines TEXT, strengths_weaknesses TEXT, matchup_notes TEXT, mulligan_guide TEXT, user_id UUID NOT NULL, updated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_documentation_user_id ON deck_documentation(user_id);
CREATE TABLE deck_notes (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE CASCADE, content TEXT NOT NULL, user_id UUID NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_notes_deck_id ON deck_notes(deck_id);
CREATE INDEX idx_deck_notes_user_id ON deck_notes(user_id);
CREATE TABLE deck_overview_content (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, content TEXT NOT NULL, user_id UUID NOT NULL, generated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_overview_content_user_id ON deck_overview_content(user_id);
CREATE TABLE deck_combos (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, content TEXT NOT NULL, user_id UUID NOT NULL, generated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_combos_user_id ON deck_combos(user_id);
CREATE TABLE deck_mana_analysis (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, content TEXT NOT NULL, user_id UUID NOT NULL, generated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_mana_analysis_user_id ON deck_mana_analysis(user_id);
CREATE TABLE deck_upgrades (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, content TEXT NOT NULL, owned BOOLEAN DEFAULT FALSE, suggested_cut TEXT, cut_flag TEXT, price NUMERIC, synergy_score DOUBLE PRECISION, user_id UUID NOT NULL, generated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_upgrades_user_id ON deck_upgrades(user_id);
CREATE TABLE deck_ratings (deck_id INTEGER PRIMARY KEY REFERENCES decks(id) ON DELETE CASCADE, content TEXT NOT NULL, user_id UUID NOT NULL, generated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_deck_ratings_user_id ON deck_ratings(user_id);;
